version: '2.0'
services:

  walmart:
    build: .
    command: python spiders.py
    links:
      - selenium
    env_file:
      - ".env"
    depends_on:
      - "selenium"

  richard:
    build: .
    command: [celery, worker, --app=worker.app, --beat, --loglevel=INFO]
    links:
      - rabbitmq
    env_file:
      - ".env"
    depends_on:
      - "rabbitmq"


  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"

  selenium:
    image: selenium/standalone-firefox
    ports:
      - "4444:4444"
