version: '2.0'
services:
  app:
    build: .
    command: python spiders.py
    volumes:
      - .:/app
    links:
      - rabbitmq
      - selenium
    env_file:
      - ".env"
    depends_on:
      - selenium

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
      
  selenium:
    image: selenium/standalone-firefox
    ports:
      - "4444:4444"
